#!/bin/bash

# Common path for all GPIO access
BASE_GPIO_PATH=/sys/class/gpio

PIN="21"
# Assign names to states
ON="1"
OFF="0"

# Utility function to export a pin if not already exported
exportPin()
{
  if [ ! -e $BASE_GPIO_PATH/gpio$1 ]; then
    echo "$1" > $BASE_GPIO_PATH/export
  fi
}

# Utility function to set a pin as an output
setOutput()
{
  echo out > $BASE_GPIO_PATH/gpio$1/direction
}

# Utility function to change state
changeState()
{
  echo $2 > $BASE_GPIO_PATH/gpio$1/value
}


exportPin $PIN
setOutput $PIN

changeState $PIN $ON
#vormeldeimpuls 
sleep 0.1
changeState $PIN $OFF

