#!/bin/bash
sudo apt-get update
sudo apt-get -y install mono-xsp4 subversion autoconf debhelper flex libusb-dev libpcsclite-dev libpcsclite1 libccid pcscd pcsc-tools libpcsc-perl libusb-1.0-0-dev libtool libssl-dev cmake checkinstall

#startscript
# Mit z.B. nano in "/etc/xdg/lxsession/LXDE-pi/autostart"
# "@/bin/bash /home/pi/startscript" am Ende einfügen

cp automat ~/Client/

#nfclib
wget https://github.com/nfc-tools/libnfc/releases/download/libnfc-1.7.0-rc7/libnfc-1.7.0-rc7.tar.gz
tar -xvzf libnfc-1.7.0-rc7.tar.gz
cd libnfc-1.7.0-rc7
./configure --with-drivers=acr122_usb
make
sudo make install
sudo sh -c "echo /usr/local/lib > /etc/ld.so.conf.d/usr-local-lib.conf"
sudo ldconfig
cd ~
gcc -o Scanner.out scanner.c -lnfc
mv Scanner.out ~/Client/
